name: interpolation_env
version: 1.0
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - ipywidgets
  - scipy
  - pandas
  - pyDOE
  - scikit-learn
  - pip
  - pip:
      - tracemalloc
      - timeit